### ISSUE TITLE
Implement IPIP-484 Delegated Routing V1 Support for Querying Specific Network Transport and Transfer Protocols

### ISSUE THREAD

**Issue by 2color** [ipfs/helia-delegated-routing-v1-http-api#143]
## Background 

We should add support for querying specific network transports and transfer protocols as defined in [IPIP-484](https://github.com/ipfs/specs/pull/484).

Boxo implementation can be found in https://github.com/ipfs/boxo/pull/671

## Why?

This will help us with delegated routing in the browser, where transports and transfer protocols are very constrained.

**Comment by SgtPooki** [comment]
I believe this was done by https://github.com/ipfs/helia-delegated-routing-v1-http-api/pull/144 and https://github.com/ipfs/helia-delegated-routing-v1-http-api/pull/147
